name: CI

on:
  push:
    branches: [main, master]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        if:
          hashFiles('requirements-dev.txt') != '' || hashFiles('pyproject.toml')
          != ''
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dev deps
        if: hashFiles('requirements-dev.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Set up Node
        if:
          hashFiles('package-lock.json') != '' || hashFiles('pnpm-lock.yaml') !=
          '' || hashFiles('yarn.lock') != ''
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Node deps
        if: hashFiles('package-lock.json') != ''
        run: npm ci

      - name: Set up Go
        if: hashFiles('go.mod') != ''
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Lint
        run: make lint

      - name: Test
        run: make test
